name = "b-komachi-ai"
main = "src/index.ts"
compatibility_date = "2023-11-12"
env = { }

[placement]
mode = "smart"

[triggers]
crons = [ ]

[vars]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
